name: Publish Power BI Report

on:
  push:
    branches:
      - main
    paths:
      - 'SQL_AND_POWERBI - Copy - Copy (2).pbix'  # Adjust the path to your report file

jobs:
  publish_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Power BI CLI
        run: npm install -g powerbi-cli

      - name: Publish Power BI Report
        run: |
          # Authenticate with Power BI service using your credentials
          pbi login -u ${{ secrets.POWER_BI_USERNAME }} -p ${{ secrets.POWER_BI_PASSWORD }}

          # Define variables for report, dataset, and workspace names
          reportName="Your Report Name"
          datasetName="Your Dataset Name"
          workspaceName="Your Workspace Name"

          # Publish the Power BI report to the Power BI service
          pbi import -f SQL_AND_POWERBI - Copy - Copy (2).pbix
          -d "$datasetName" -r "$reportName" -g "$workspaceName"
