name: Power BI Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    - name: Deploy to Power BI Service
      if: github.ref == 'refs/heads/main'
      run: |
       # Access GitHub Secrets for Power BI credentials
       $powerBiUsername = ${{ secrets.POWER_BI_USERNAME }}
       $powerBiPassword = ${{ secrets.POWER_BI_PASSWORD }}

 

      # Call your PowerShell script or command to deploy to Power BI
      # Replace the comments with actual deployment commands
      #./deploy-to-powerbi.ps1 $powerBiUsername $powerBiPassword
    
